deployment:
  tasks:
    # This is the most efficient method: use 'rsync' to copy files
    - /bin/rsync -a --delete . $DEPLOYMENT_PATH/



### Resource: 
# - https://docs.cpanel.net/knowledge-base/web-services/guide-to-git-deployment/#overview